DELETE FROM games;
DELETE FROM SQLITE_SEQUENCE WHERE name='games';
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("b001", "Wolrd of Warcaraft", "2p,3p,4p,5p,6p,7p,8p,9p,10p,11p,12p,MMO");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("b002", "Hearthstone", "2p");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("b003", "Heros of the Storm", "2p,3p,4p");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("b004", "Overwatch", "2p,3p,4p");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("b005", "Destiny 2", "2p,3p,4p,5p,6p");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("b006", "Battlefield 1 Revolution", "2p,3p,4p");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("b007", "Battlefield 1 Incursions", "2p,3p,4p");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("b666", "Diablo III", "2p,3p,4p");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("dnd", "Dungeons and Dragons", "3p,4p,5p,6p");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("e001", "Plants Vs. Zombies: Garden Warfare", "2p,3p,4p");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("e002", "Plants Vs. Zombies: Garden Warfare 2", "2p,3p,4p");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("e003", "Titanfall", "2p,3p,4p");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("g001", "Guildwars 2", "2p,3p,4p,MMO");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("m001", "Minecraft", "2p,3p,4p");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("s001", "STAR WARS: The Old Republic Knights of the Eternal Throne", "2p,3p,4p");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("s002", "Star Citizen", "2p,3p,4p");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("300","Day of Defeat: Source","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("4000","Garry's Mod","4p");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("4560","Company of Heroes - Legacy Edition","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("6370","Bloodline Champions","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("8500","EVE Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("9880","Champions Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("9900","Star Trek Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("9930","Test Drive Unlimited 2","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("11020","TrackMania Nations Forever","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("11610","Dragon Nest","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("17020","Global Agenda","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("17080","Tribes: Ascend","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("17500","Zombie Panic! Source","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("17570","Pirates, Vikings, and Knights II","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("20500","Red Faction Guerrilla Steam Edition","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("21170","Gotham City Impostors","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("24010","Train Simulator","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("24200","DC Universe Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("24960","Battlefield: Bad Company 2","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("31280","Poker Night at the Inventory","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("34900","Bad Rats: the Rats' Revenge","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("36620","Forsaken World","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("38830","CrimeCraft: GangWars","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("39000","Moonbase Alpha","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("39120","RIFT","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("39210","FINAL FANTASY XIV Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("42160","War of the Roses","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("42680","Call of Duty: Modern Warfare 3","4p");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("42700","Call of Duty: Black Ops","4p");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("42710","Call of Duty: Black Ops","4p");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("47410","Stronghold Kingdoms","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("47870","Need For Speed: Hot Pursuit","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("51100","Tactical Intervention","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("99900","Spiral Knights","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("99910","Puzzle Pirates","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("102700","A.V.A. Alliance of Valiant Arms","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("104700","Super MNC","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("107900","War Inc. Battlezone","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("109400","MicroVolts Surge","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("109600","Neverwinter","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("113400","APB Reloaded","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("113420","Fallen Earth Free2Play","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("200110","Nosgoth","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("200210","Realm of the Mad God","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("201230","EverQuest II Free-To-Play. Your Way.","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("202090","Magicka: Wizard Wars","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("202970","Call of Duty: Black Ops II","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("202990","Call of Duty: Black Ops II","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("203290","America's Army: Proving Grounds","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("205710","Everquest ","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("206210","Gotham City Impostors Free to Play","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("206480","Dungeons & Dragons Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("206500","AirMech Strike","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("207230","ArcheBlade","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("208090","Loadout","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("209080","Guns of Icarus Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("209710","War of the Immortals","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("209870","Blacklight: Retribution","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("211500","RaceRoom Racing Experience","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("212070","Star Conflict","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("212160","Vindictus","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("212180","Combat Arms","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("212200","Mabinogi","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("212240","Atlantica","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("212390","Continent of the Ninth Seal","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("212500","The Lord of the Rings Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("214190","Minimum","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("214420","Gear Up","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("215080","WAKFU","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("215100","Ragnarok Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("215120","ROSE Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("215280","Secret World Legends","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("215470","Primal Carnage","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("215830","Closers","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("215870","Dungeon-Party","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("216150","MapleStory","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("217750","Age of Conan: Unchained","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("218170","Age of Conan: Unchained - US version","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("218230","PlanetSide 2","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("218450","Jagged Alliance Online - Steam Edition","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("219700","Dogs of War Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("219870","Football Superstars","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("221100","DayZ","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("222520","Champions of Regnum","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("223410","Perpetuum","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("223650","F.E.A.R. Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("223710","Cry of Fear","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("223750","DCS World","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("224260","No More Room in Hell","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("224540","Ace of Spades: Battle Builder","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("224600","Defiance","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("225840","Sven Co-op","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("226320","Marvel Heroes Omega","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("226700","Infestation: Survivor Stories Classic","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("227180","Kingdom Wars","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("227700","Firefall","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("227940","Heroes & Generals","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("229100","Dragon's Prophet","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("230330","FINAL FANTASY XI: Ultimate Collection Seekers Edition","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("230350","FINAL FANTASY XI: Ultimate Collection Seekers Edition ROW","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("230410","Warframe","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("231060","Ragnarok Online 2","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("231430","Company of Heroes 2","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("233630","Ascend: Hand of Kul","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("235340","Prime World","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("235380","Blitzkrieg 3","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("235400","Kings Bounty: Legions","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("236110","Dungeon Defenders II","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("236390","War Thunder","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("237310","Elsword","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("237870","Planet Explorers","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("238960","Path of Exile","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("239220","The Mighty Quest For Epic Loot","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("239660","Soldier Front 2","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("240320","Panzar","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("240380","Solstice Arena","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("241560","The Crew","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("242720","GunZ 2: The Second Duel","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("244770","StarMade","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("244930","SNOW","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("245130","The Dead Linger","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("246280","Happy Wars","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("247730","Nether: Resurrected","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("249550","NEStalgia","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("249570","The Castle Doctrine","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("250420","8BitMMO","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("250740","Ragnarok Online - Free to Play - European Version","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("251950","WWII Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("253490","CABAL Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("253710","theHunter Classic","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("254300","Dofus","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("255500","Entropy","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("257730","Infinity Wars: Animated Trading Card Game","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("258160","Rise of Incarnates","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("259020","Dragon's Prophet","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("259080","Just Cause 2: Multiplayer Mod","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("260430","The Four Kings Casino and Slots","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("263060","Blockstorm","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("263500","Dragons and Titans","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("263540","Villagers and Heroes","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("264120","Victory: The Age of Racing","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("264360","La Tale","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("265630","Fistful of Frags","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("265770","Cannons Lasers Rockets","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("266070","City of Steam: Arkadia","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("266150","Lost Saga NA","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("266410","iRacing","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("267750","Shadowrun Chronicles - Boston Lockdown","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("268420","Aura Kingdom","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("269210","Hero Siege","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("269530","Voice of Pripyat","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("270150","RUNNING WITH RIFLES","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("270880","American Truck Simulator","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("271290","HAWKEN","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("272230","Sub Rosa","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("272350","Tom Clancy's Ghost Recon Phantoms - EU","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("273110","Counter-Strike Nexon: Zombies","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("277430","Halo: Spartan Assault","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("277950","Deadbreed","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("280620","Fiesta Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("280790","Creativerse","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("283060","Lucent Heart","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("283100","Colonies Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("283920","Putt-Putt Joins the Parade","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("283940","Freddi Fish and The Case of the Missing Kelp Seeds","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("286940","S.K.I.L.L. - Special Force 2 (Shooter)","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("287140","Selfie : Sisters of the Amniotic Lens","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("287920","Mortal Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("289780","Requiem: Rise of the Reaver","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("290080","Life is Feudal: Your Own","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("290140","Echo of Soul","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("290710","Cloud Chamber","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("290730","My Lands: Black Gem Hunting","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("291210","UberStrike","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("291480","Warface","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("291550","Brawlhalla","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("293280","Wander","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("293400","Epic Space: Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("293500","Amazing World","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("293540","Guns and Robots","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("293560","TOME: Immortal Arena","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("294660","Putt-Putt Saves the Zoo","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("295110","Just Survive","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("295550","Royal Quest","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("295710","Darkwind: War on Wheels","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("295950","NO NAME GIVEN8027810000","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("296300","Ballistic Overkill","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("297470","Xsyon - Prelude","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("297810","Landmark","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("298160","Eldevin","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("298300","UFO Online: Fight for Earth","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("299360","Block N Load","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("299700","Face of Mankind","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("299740","Miscreated","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("300040","Divine Souls F2P MMO","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("300970","Fiesta Online NA","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("301520","Robocraft","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("302270","Dungeon Defenders Eternity","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("302590","Of Guards And Thieves","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("302830","BLOCKADE 3D","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("304030","ArcheAge","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("304050","Trove","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("304930","Unturned","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("306130","The Elder Scrolls Online: Tamriel Unlimited","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("306830","Zombies Monsters Robots (ZMR)","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("306930","BattleSpace","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("307290","Velvet Sundown","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("308520","Minimon","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("310380","Fractured Space","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("311310","Naval Action","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("312150","Wild Warfare","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("312210","The Fifth Day","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("313160","Farming Simulator 15","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("313340","Mountain","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("313740","Sakura Spirit","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("314000","Pool Nation FX Lite","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("314160","Microsoft Flight Simulator X: Steam Edition","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("314280","The Forgotten Ones","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("315640","Dizzel","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("316390","sZone-Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("317110","Uncharted Waters Online: Age of Revolution","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("317470","Cubic Castles","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("318100","AXYOS","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("319400","Disney Winnie the Pooh","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("319730","GRANADO ESPADA","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("320300","Car Mechanic Simulator 2015","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("320590","Warside","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("321350","Fairspace","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("321360","Primal Carnage: Extinction","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("322300","The Repopulation","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("322780","Worlds Adrift","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("323370","TERA","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("324510","Boundless","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("324790","LEGO Minifigures Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("324810","TOXIKK","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("326160","Shroud of the Avatar: Forsaken Virtues","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("326360","Warspear Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("326460","ShellShock Live","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("327070","Gloria Victis","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("327090","Out of Reach","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("327690","Gigantic","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("328060","Tales Runner","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("330210","Asteroids: Outpost","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("330880","Redemption","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("332070","School of Dragons","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("332500","GRAV","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("332650","The Exiled","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("332970","Storm United","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("333340","Star Rangers XE","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("333600","NEKOPARA Vol. 1","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("333930","Dirty Bomb","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("334230","Town of Salem","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("334290","Gates of Horizon","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("335050","World Of Leaders","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("335150","Magic Barrage - Bitferno","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("335240","Transformice","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("335330","Brick-Force","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("335820","Dream Of Mirror Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("335900","Angels of Fasaria: Version 2.0","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("336510","Anno Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("336520","Might & Magic Heroes Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("336790","KWAAN","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("337410","Karos","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("337950","The SKIES","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("338540","Navy Field 2 : Conqueror of the Ocean","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("338640","Subsiege","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("339280","Strife","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("339530","Factions: Origins of Malu","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("339600","VEGA Conflict","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("339610","Freestyle 2: Street Basketball","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("339860","AoF World Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("340300","Teddy Floppy Ear - Mountain Adventure","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("340540","TDP4:Team Battle","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("340810","Deepworld","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("342150","games (appid,name,tags) of Glory","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("342200","MechWarrior Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("342280","Manyland","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("342570","HIS (Heroes In the Sky)","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("343630","CroNix","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("345010","Ascent - The Space Game","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("346110","ARK: Survival Evolved","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("346120","Boring Man - Online Tactical Stickman Combat","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("346220","Lif","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("346440","Musclecar Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("347630","16 Bit Arena","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("348670","Immune - True Survival","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("349220","The Black Watchmen","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("349450","Dark Forester","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("349700","Romero's Aftermath","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("349720","Audition Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("350660","Alganon","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("350700","Red Stone Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("351040","Moonrise","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("351140","Rustbucket Rumble","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("351290","Survival: Postapocalypse Now","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("352460","Dead Realm","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("352700","Subspace Continuum","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("353130","Time of Dragons","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("353360","how do you Do It?","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("354200","Aberoth","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("354290","LoveBeat","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("355070","TDP5 Arena 3D","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("355120","Pirates Deck","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("355180","Codename CURE","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("355840","Survarium","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("356130","Heroes of Scene","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("356330","Dragomon Hunter","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("356640","Metro Conflict","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("357320","Break_In","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("357480","Frozen Free Fall: Snowball Fight","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("357500","Rumble Fighter: Unleashed","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("359050","Shower With Your Dad Simulator 2015: Do You Still Shower With Your Dad","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("359320","Elite Dangerous","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("359550","Tom Clancy's Rainbow Six Siege","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("359800","Copa Petrobras de Marcas","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("359960","Choice Chamber","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("360590","Once Bitten, Twice Dead!","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("360730","Cards and Castles","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("360760","Run and Fire","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("360870","Ultimate Tic-Tac-Toe","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("361800","Tree of Life","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("362070","Metal Reaper Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("362300","Just Survive Test Server","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("363970","Clicker Heroes","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("364110","Swordsman","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("365590","Tom Clancys The Division","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("365620","WarBirds - World War II Combat Aviation","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("366160","Hounds : The Last Hope","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("366220","Wurm Unlimited","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("366860","Spy Bugs","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("368720","Sirius Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("368750","Nebula Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("369200","Ghost in the Shell: Stand Alone Complex - First Assault Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("369400","Let the Cat in","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("370100","Uncrowded","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("371180","Super 3-D Noah's Ark","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("371310","Karos Returns","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("371660","Far Cry Primal","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("372000","Tree of Savior (English Ver.)","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("372800","RPG MO","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("373080","Instinct","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("373100","Wrath of Athena","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("373330","All Is Dust","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("373680","Aion","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("373700","Lineage II","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("373720","Ryzom","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("374670","Ember Strike","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("375230","Warhammer 000 : Eternal Crusade","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("375900","Trackmania Turbo","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("376120","Assault Corps 2","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("376140","SAGA","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("376210","The Isle","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("376310","Otherland MMO","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("376570","WildStar","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("377140","Hide & Hold Out - H2o","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("378480","Badland Bandits","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("380600","Fishing Planet","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("380770","Wind of Luck: Arena","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("380840","Teeworlds","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("381180","Edengrad","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("381640","Allods Online RU","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("381990","Dragon Saga","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("382850","Piercing Blow","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("383980","Rivals of Aether","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("384030","Florensia","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("384180","Prominence Poker","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("385020","AoF Chess Club 2.0","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("385530",":  ","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("385880","Gladiators Online: Death Before Dishonor","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("385890","Golden Rush","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("386180","Crossout","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("386360","SMITE","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("386640","Affected Zone Tactics","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("387450","Shadow of Kingdoms","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("388370","Nova Blitz","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("389040","Project Genom","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("389430","Knight Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("389530","Garlock Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("389570","Mitos.is: The Game","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("390100","9Dragons","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("390540","High Fidelity","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("390670","Steel Ocean","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("391240","Forgotten Lore","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("391460","WARMODE","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("393380","Squad","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("393410","World of Soccer online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("394120","Atom Universe","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("394380","BattleStick","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("394690","Tower Unite","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("396280","Anarchy Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("396390","Barbie and Her Sisters Puppy Rescue","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("397040","Sphere III: Enchanted World","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("397060","Faeria","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("397900","Business Tour - Online Multiplayer Board Game","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("398970","Fasaria World: Browser MO","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("399660","Battle Battalions","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("400250","Heaven Island - VR MMO","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("402450","Linkrealms","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("402570","Atlas Reactor","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("402710","Osiris: New Dawn","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("405980","Legend of Dungeon: Masters","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("407060","AltspaceVRThe Social VR App","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("407090","Heroes and Titans: Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("407250","Pro Evolution Soccer 2016 myClub","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("407510","Devilian","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("407530","ARK: Survival Of The Fittest","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("407700","Lonath Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("407730","Dungeons Of Kragmor","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("409510","Genesis Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("410380","HEX: Shards of Fate","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("410490","Elements: Epic Heroes","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("410560","Trinium Wars","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("412400","GASP","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("412450","The Black Death","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("412470","Metal War Online: Retribution","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("412880","Drift Streets Japan","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("412940","Back to Dinosaur Island","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("413110","Hero's Song","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("414530","Skyforge","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("415270","Star Crusade CCG","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("415660","Tiger Knight","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("415860","Tactical Craft Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("416450","Emporea: Realms of War and Magic","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("417910","Street Warriors Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("418030","Subsistence","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("418110","March of War: FaceOff - XL","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("418460","Rising Storm 2: Vietnam","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("419520","Lifeless","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("420110","NEKOPARA Vol. 2","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("420790","StarBreak","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("421030","Catch Me","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("421700","Sakura Santa","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("421960","World of Fishing","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("422940","Divergence: Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("423890","Gods and Idols","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("424780","Imperia Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("426560","Full Tilt Poker","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("426970","Age of Magic CCG","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("427270","Orcs Must Die! Unchained","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("428180","Islet Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("428940","CONTASION 2","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("429020","LONE WOLF: Horizon","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("429680","Spellweaver","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("429790","AdventureQuest 3D","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("430440","Of Kings And Men","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("431240","Golf With Your Friends","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("432290","Elemental Heroes","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("433130","WarBirds Dogfights 2016","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("433350","BlackShot: Mercenary Warfare FPS","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("433530","Heliborne","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("433850","H1Z1","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("434380","Pixel Z - Gun Day","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("435440","Galaxy Control: 3D Strategy","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("436150","Governor of Poker 3","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("436560","Kings and Heroes","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("437220","The Culling","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("438040","Shakes and Fidget","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("438100","VRChat","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("438600","Soccer Manager","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("438720","Heroes of Shadow Guard","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("439350","Kritika Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("439370","Midair","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("439700","H1Z1 Test Server","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("440900","Conan Exiles","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("442080","Riders of Icarus","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("442110","Perfect World International","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("442710","Fantasy Tales Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("442810","UFO Online: Invasion","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("443080","Elite Dangerous: Arena","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("443110","Armored Warfare","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("444090","Paladins","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("444200","World of Tanks Blitz","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("444490","POLYWAR","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("444640","Bloons TD Battles","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("446150","GUNS UP!","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("446270","UnnyWorld - Battle Royale","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("447500","Shattered Skies: Prologue","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("448150","Mystica: The Ninth Society","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("448460","Crazy Killer","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("449470","Atulos Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("451130","Khan: Absolute Power","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("453000","TheWaveVR Beta","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("453270","Madness Cubed","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("454070","Boundel: The Second Era","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("454540","LuckCatchers","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("454600","Age of Cavemen","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("454650","DRAGON BALL XENOVERSE 2","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("454910","Twin Saga","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("455020","Jackpot Poker by PokerStars","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("457330","High Octane Drift","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("457590","Luna Online: Reborn","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("458960","Winning Putt: Golf Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("459160","Allods Online My.com","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("460920","Steep","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("461180","SurrealVR","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("461210","Riding Out","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("461910","Forge of Gods (RPG)","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("462440","ROKH","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("463000","Hero Battle","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("463680","Guardians of Ember","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("464070","Diorama Battle of NINJA3D ","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("464350","Screeps","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("466220","Kingdom of Loot","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("466660","Stash","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("466910","Worm.is: The Game","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("467570","TITANS: Dawn of Tribes","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("467810","Splody","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("468070","90 Minute Fever - Football (Soccer) Manager MMO","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("468250","Warfare Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("468920","Ultimate Fishing Simulator","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("469920","hackmud","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("469930","Pandum online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("470040","Spellgear","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("471710","Rec Room","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("473690","Absolver","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("473810","Killbot","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("474790","BATTLE PIXEL'S SURVIVAL GROUND","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("475100","Kalonline","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("475630","Crush Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("476480","Heaven Forest - VR MMO","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("476600","Call of Duty: WWII","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("476620","Call of Duty: WWII","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("479130","ESEA","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("482920","Hero Zero","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("483850","Guns N' Boxes","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("486160","Berserk: The Cataclysm","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("486310","Meadow","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("487120","Citadel: Forged with Fire","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("488440","Angeldust","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("489000","The Infinite Black","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("489560","Astroflux","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("489570","Antisphere","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("491260","Take Thy Throne","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("493440","Thanatos","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("495350","Woodle Tree 2: Worlds","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("495580","Divided We Fall","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("495910","Dungeon Fighter Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("497270","MIGHT","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("497860","Zezenia Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("497940","Destiny of Ancient Kingdoms","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("500710","Wild Terra Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("501740","Dropship Down","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("502550","Strike.is: The Game","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("503010","Azulgar Star Commanders","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("503240","Hurricane","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("503340","Dig 4 Destruction","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("504300","Gangs of Space","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("505460","Foxhole","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("505700","Anyland","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("506140","Shop Heroes","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("506540","Last Man Standing","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("509560","Heroes of Dire","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("510660","Big Bang Empire","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("510840","Evolvation","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("511800","ONRAID","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("512200","Metal Carnage","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("513440","Path of War","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("513880","Panzer Warfare","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("516510","Orake 2D MMORPG","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("518660","Zone4","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("518790","theHunter: Call of the Wild","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("520530","INTERSHELTER","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("520860","Impulse of War","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("521330","Tuebor: I Will Defend","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("523190","Weapons of Mythology - New Age -","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("523740","Techwars Online 2","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("523760","Loot or Die","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("524970","Helmet Heroes","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("527950","Divergence: Year Zero","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("528460","Rogalia","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("528740","Operation: New Earth","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("529180","Dark and Light","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("530300","Slymes","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("530560","STEAM HAMMER","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("530700","Argo","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("530900","emoj.io","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("531640","Eternal Card Game","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("534500","Tiger Knight: Empire War","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("534820","Heroes Evolved","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("535440","WAR7","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("536950","Legend of Ares","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("537180","Digimon Masters Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("538100","Feel The Snow","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("539640","Racecar.io","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("539650","TwelveSky 2 Classic","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("541190","Nodiatis","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("541300","Survive the Nights","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("542480","Therian Saga","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("542590","SoulSaverOnline","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("542940","Kickoff Legends","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("546660","Operation Breakout","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("547410","Peak Angle: Drift Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("547810","Spacewing VR","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("548080","Space Merchants: Arena","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("548290","Dark Eden","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("550470","NosTale","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("550650","Black Squad","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("550900","Metin2","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("552110","Puzzle Pirates: Dark Seas","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("552990","World of Warships","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("553290","Drift King: Survival","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("555570","Infestation: The New Z","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("557780","Atom Fishing II","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("559310","Illyriad - Grand Strategy MMO","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("559340","Sunset Rangers","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("559460","Cloud Pirates","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("562010","Tanki Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("562590","Galactic Junk League","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("562700","Paintball 707","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("562840","Dragon Blood","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("564710","Soda Dungeon","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("565020","Global Adventures","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("568580","GunFleet","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("568810","FreeStyleFootball","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("569720","TUNNEL DIVERS","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("574070","Space Wars: Interstellar Empires","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("574080","Fog of War","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("575720","Mighty Party","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("576940","Hunt For Gods","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("578080","PLAYERUNKNOWN'S BATTLEGROUNDS","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("578120","Slash Arena: Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("578310","BRAIN / OUT","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("579010","goalunited PRO  football manager for experts","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("580150","Xbird","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("582660","Black Desert Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("583740","AVATARIKA","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("588120","Capsa","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("588210","HELLION","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("589290","Holdfast: Nations At War","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("589430","Killer Elite  Time to Die","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("591530","Hyper Universe","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("591740","Sniper Fury","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("593620","The Last Conflict","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("598680","Master of Magic Chess","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("599060","Age of Heroes: Conquest","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("602090","Janus VR","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("604190","Storm Riders","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("604530","EmbodyMe Beta","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("605230","Grey Hack","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("607200","Tanki X","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("609940","KROSMAGA","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("611800","Jidousha Shakai","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("611830","Park Bound","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("612290","ASTA Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("614860","XAOC","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("614970","Qbike: Cyberpunk Motorcycles","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("615050","Burst The Game","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("616090","NO NAME GIVEN2376410000","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("616220","Hide vs. Seek","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("619310","Ways of History","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("619910","Just Cause 3: Multiplayer Mod","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("621880","Phoenix Dynasty 2","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("622310","Amigo VR","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("622470","Road Dogs","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("623310","Arcfall","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("623880","World of Speed","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("624910","3on3 FreeStyle","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("625140","Ragnarok Journey","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("628870","Soccer Manager Arena","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("635260","CarX Drift Racing Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("636040","Pixel Worlds","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("636480","Ravenfield","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("638920","BeanVRThe Social VR APP","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("644100","RUN ROOMS","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("644310","BALLOON Saga","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("645630","Car Mechanic Simulator 2018","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("645830","Son Korsan","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("646820","Might & Mayhem","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("647530","Prime Arena","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("647740","Airmen","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("648070","CrisisActionVR","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("649870","NitroRage","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("651090","Aces High III","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("652980","Loading Screen Simulator","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("656070","Better Off Tread","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("657630","Fidget Spinner","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("658510","Dark Eden Origin","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("658980","Valnir Rok Survival RPG","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("659350","Cowboy Revenge","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("660330","Ragnarok RE:START","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("660880","b","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("661960","Dragon Lords: 3D Strategy","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("662320","METRO CONFLICT: THE ORIGIN","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("663090","Granado Espada For SEA","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("663110","Sunrise: survival","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("663390","Rento Fortune - Online Dice Board Game","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("666860","Bit Heroes","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("669580","The Ultimatest Battle","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("671310","Pararea Beta","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("672680","Call of War","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("673260","Starblast","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("673940","Dragon Glory","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("674400","Einar","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("675230","Secondhand Lands","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("675560","NAVYFIELD","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("679270","Antaria Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("681160","Breach of Contract Online","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("681860","Wild Buster: Heroes of Titan - MMO-ARPG","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("684720","Battlegun","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("688430","Duel of Summoners: The Mabinogi Trading Card Game","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("690460","Sky Hunter","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("692060","Casinopia: The Blackjack","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("695690","Ancient Siberia","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("696370","BROKE PROTOCOL: Online City RPG","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("700030","Life is Feudal: MMO","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("702320","March of Empires","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("703060","connect - Virtual Home (3D or VR)","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("703090","(Adventure Road)","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("703950","Just Fishing","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("704060","Mystic Miracles - Strategy card board game","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("705810","Wuxing Master(CCG)","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("708510","The Promethium Effect - The Idle Clicker MMO","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("715310","Urban Rivals","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("719640","War Planet Online: Global Conquest","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("721030","La Tale - Evolved","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("723780","Modern Combat Versus","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("727500","WAR DRONES","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("731640","Knife Battles","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("732110","OneScreen Wagons","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("732730","Red Crucible: Reloaded","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("734550","Wheel Riders Online OBT","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("734580","BattleRush","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("737750","PLAYERUNKN4WN: Zombie","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("746930","OrbusVR","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("748370","STAND OUT : VR Battle Royale","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("754350","2","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("756360","LINCH","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("759700","PLAYERUNKN1WN: Friendly Fire","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("666","Diablo III","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("107410","Arma 3","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("361420","Astroneer","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("346010","Besiege","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("204360","Castle Crashers","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("50300","Spec Ops: The Line","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("207140","SpeedRunners","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("211820","Starbound","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("286160","Tabletop Simulator","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("440","Team Fortress 2","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("322330","Don't Starve Together","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("379720","Doom","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("262280","Dungeons 2","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("383120","Empyrion - Galactic Survival","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("289130","Endless Legend","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("208140","Endless Space","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("427520","Factorio","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("229810","A Fistful of Gun","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("271590","Grand Thef Auto V","2p,3p,4p,8p");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("219990","Grim Dawn","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("281610","Homeworld: Deserts of Kharak","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("222880","Insurgency","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("331670","The Jackbox Party Pack","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("550","Left 4 Dead 2","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("332310","Lego Worlds","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("226720","Lost Planet 3","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("349480","Modular Combat","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("254440","Pool Nation","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("252950","Rocket League","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("252490","Rust","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("206420","Saints Row IV","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("8930","Sid Meier's Civilization V","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("460930","Tom Clancy's Ghost Recon Wildlands","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("45760","Ultra Street Fighter IV","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("235540","Warhammer: End Times - Vermintide","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("447040","Watch_Dogs 2","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("99999","Test Test","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("570","Dota 2","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("730","Counter-Strike: Global Offensive","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("218620","PAYDAY 2","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("289070","Sid Meier's Civilization VI","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("105600","Terraria","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("594570","Total War: WARHAMMER II","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("381210","Dead by Daylight","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("236850","Europa Universalis IV","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("394360","Hearts of Iron IV","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("281990","Stellaris","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("435150","Divinity: Original Sin 2","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("221380","Age of Empires II HD","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("678950","DRAGON BALL FighterZ","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("251570","7 Days to Die","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("601510","Yu-Gi-Oh! Duel Links","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("48700","Mount & Blade: Warband","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("447020","Farming Simulator 17","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("214950","Total War: ROME II - Emperor Edition","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("49520","Borderlands 2","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("489940","BATTALION 1944","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("268500","XCOM 2","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("240","Counter-Strike: Source","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("504370","Battlerite","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("477160","Human: Fall Flat","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("203770","Crusader Kings II","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("325610","Total War: ATTILA","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("244850","Space Engineers","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("364360","Total War: WARHAMMER","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("239140","Dying Light","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("453480","Shadowverse CCG","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("4700","Medieval II: Total War","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("41060","Serious Sam Classic: The Second Encounter","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("41050","Serious Sam Classic: The First Encounter","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("270370","Lambda Wars Beta","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("705220","Tactical Monsters Rumble Arena","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("291410","Duelyst","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("293260","Card Hunter","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("329110","Gems of War - Puzzle RPG","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("667870","MINDNIGHT","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("294160","Galcon 2: Galactic Conquest","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("449140","Istrolid","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("434510","Formicide","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("31700","Iron Grip: Warlord","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("438680","One Troll Army","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("630","Alien Swarm","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("8850","BioShock 2","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("41300","Altitude","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("466240","Deceit","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("519860","DUSK","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("238460","BattleBlock Theater","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("291860","Pit People","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("342560","Airships: Conquer the Skies","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("434570","Blood and Bacon","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("512900","Streets of Rogue","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("405830","Turok 2: Seeds of Evil","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("428080","Racket: Nx","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("512490","Zombie Estate 2","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("308600","Geneshift","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("647960","Rusted Warfare - RTS","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("432980","INVERSUS Deluxe","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("529520","Mutant Football League","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("595430","Sky Knights","");
INSERT OR REPLACE INTO games (appid,name,tags) VALUES("607460","Epic Snails","");
CREATE UNIQUE INDEX IF NOT EXISTS games_appid ON games (appid);